### ISSUE TITLE
Error saving floorplan

### ISSUE THREAD

**Issue by macumber** [NatLabRockies/floorspace.js#103]
I am getting this error in the 0.2.0 build, I haven't tested extensively but it appears that the save fails when there is an image that has been imported

![image](https://user-images.githubusercontent.com/1327850/28276503-6107e8e0-6ad4-11e7-8b3c-bd0c99fada25.png)

**Comment by shorowit** [comment]
Same as https://github.com/NREL/openstudio-geometry-editor/issues/87?

**Comment by macumber** [comment]
Duplicate
