### ISSUE TITLE
Mode to find unshared edges

### ISSUE THREAD

**Issue by macumber** [NatLabRockies/floorspace.js#104]
A mode which would show all edges that are shared by 1 vs 2 spaces would be very helpful.  Edges that are shared by only one space will be translated to exterior walls, we want to make sure no interior walls are accidentally classified as exterior

**Comment by DavidGoldwasser** [comment]
Could use preview and render by boundary condition, but would be more slick if in the 2d editor. Oh, well I guess the with the surface search you can't turn off the outside walls to see just interior surfaces, so would have to step through one story at a time.

**Comment by macumber** [comment]
The issues here are for FloorspaceJS only, so this would apply in the 2D mode

**Comment by shorowit** [comment]
Maybe we could use thick lines for exterior walls and thin lines for interior walls? Probably wouldn't even need to be a mode.

**Comment by macumber** [comment]
I like that

**Comment by bgschiller** [comment]
Thinking about this plan. A couple issues I'm looking at:

We're already using thick lines to indicate the 'selected' space. 
![](https://trello-attachments.s3.amazonaws.com/58d428743111af1d0a20cf28/5ad61e9ec72035b60ce5701b/bdfc3bce8c01446ad9295f3354e86bff/capture.png)

Window-wall ratio and repeating windows could cover the exterior wall indicators:
![](https://trello-attachments.s3.amazonaws.com/58d428743111af1d0a20cf28/5ad61eecca2cc14cc923ba33/5379993452ec89b4fe05c84b020d8518/capture.png)

How would you feel about a thin dotted border outside of where the windows could appear?
![](https://trello-attachments.s3.amazonaws.com/58d428743111af1d0a20cf28/5ad61fe6b65f9b3191836e94/ec3fbbca13d00dfd20e7a104151e6150/capture.png)

**Comment by bgschiller** [comment]
notes from phone discussion:
- we'll use dotted black lines for interior walls
- solid black lines for exterior walls
- 'currently selected' should have a different color border (maybe blue, and twice as thick)

**Comment by shorowit** [comment]
Looks like a definite improvement, though I see nothing change when a space is selected.

**Comment by shorowit** [comment]
It seems like the convention is not preserved on the below-story space outlines. (I actually have no idea how it's choosing solid vs dashed for the below-story spaces right now.)

![image](https://user-images.githubusercontent.com/5861765/39646893-32a5be0e-4f9a-11e8-851d-cceab9352751.png)

![image](https://user-images.githubusercontent.com/5861765/39646902-35b479c8-4f9a-11e8-991c-ec9cbec17e39.png)

**Comment by bgschiller** [comment]
Oof. I had forgotten about how previous story spaces are shown with dotted borders. Any suggestions on how it should look?

How about same dotted/solid rules as for currently selected story, but the lines are gray instead of black?

**Comment by shorowit** [comment]
Sounds great to me!

**Comment by macumber** [comment]
Looks great!
