### ISSUE TITLE
Drawing operation deletes all geometry

### ISSUE THREAD

**Issue by macumber** [NatLabRockies/floorspace.js#105]
I've hit this a couple of times in the 0.2.0 build.  When you have an existing space and then try to draw some additional geometry that will combine with the space, sometimes the space geometry for the entire story.  The edges and vertices are still there (see image) but the faces are all gone

![image](https://user-images.githubusercontent.com/1327850/28277140-356785d6-6ad6-11e7-8805-ab26e9b52267.png)

**Comment by bgschiller** [comment]
This sounds really frustrating. I'm having a hard time reproducing it, unfortunately. Any details you can give us about what else was going on when it happened are appreciated :)

**Comment by ljbrackney** [comment]
I have seen geometry associated with other spaces vanish when drawing new geometry. I have not seen ALL geometry deleted. I observed this as recently as this morning with the new merge to develop.

**Comment by ljbrackney** [comment]
Here's my latest example.  I draw Space 1-6, and adjacent Space 1-4 (it was sitting between 1-1 and 1-6) vanishes from the editor.  The object is obviously still there.  This happens fairly frequently.

![vanish](https://user-images.githubusercontent.com/2230150/28897054-e23a8a82-7793-11e7-9238-17fe663e277c.png)

**Comment by macumber** [comment]
Might be related to https://github.com/NREL/openstudio-geometry-editor/issues/151 but might be another issue with similar symptoms.  When reporting these types of crashes we should post the console output to help developers

**Comment by macumber** [comment]
Sounds like this is not related to #151
