### ISSUE TITLE
Map placement search / done button can be confusing

### ISSUE THREAD

**Issue by macumber** [NatLabRockies/floorspace.js#106]
I mistakenly entered an address to search for then hit the done button thinking it was a search button.  Seems like we might want to separate the search and done buttons.

**Comment by ljbrackney** [comment]
+1  I learned that early on, but agree it would be nice to separate searching and acceptance.

**Comment by bgschiller** [comment]
@macumber @ljbrackney how do we feel about this?
![](https://trello-attachments.s3.amazonaws.com/58d428743111af1d0a20cf28/5980a66898bccc5d39fa1e58/e9451f8352bbd753c12ac515690cdea6/capture.png)

This code is in PR #117

**Comment by ljbrackney** [comment]
I think putting it down next to the text that says "Click 'Done' when finished" is probably a good idea.

**Comment by bgschiller** [comment]
This is done on develop.
