### ISSUE TITLE
Story Height Doesn't Appear to be Respected

### ISSUE THREAD

**Issue by ljbrackney** [NatLabRockies/floorspace.js#107]
Setting a the floor height, saving, and viewing in the previewer shows a very flat building regardless of the height specified.

![height1](https://user-images.githubusercontent.com/2230150/28327549-99f3cf42-6b98-11e7-902a-bd60b5545fcc.png)

![height2](https://user-images.githubusercontent.com/2230150/28327553-9f0df5de-6b98-11e7-901b-7b4e662e3f5a.png)

**Comment by macumber** [comment]
This is likely an error in the translator, could confirm by checking that the field is set in the floorplan.json.  If it is a translator issue those should be added to openstudio issues, possibly with a new geometry label

**Comment by ljbrackney** [comment]
Floor to ceiling height is set in the JSON, so it looks like the problem is in the Measure.  I'll leave this open and we can move it later.

**Comment by macumber** [comment]
Moved to OpenStudio issue https://github.com/NREL/OpenStudio/issues/2740
