### ISSUE TITLE
Multiple Spaces Selected and Strange Behavior

### ISSUE THREAD

**Issue by ljbrackney** [NatLabRockies/floorspace.js#120]
This is another behavior I see frequently.  Sorry the title isn't more clear, but hopefully the description and screenshot will help.

I went ahead and created a new space 1-7 and began drawing it vertically off of 1-6.  Note in the UI that BOTH 1-6 and 1-7 are selected somehow, and the editor is confused about what to do with the new Space.  It appears that it's doing some sort of subtraction from 1-6.

![multiselect](https://user-images.githubusercontent.com/2230150/28897324-0eefd4a0-7795-11e7-8f4e-fe330f5e5b9d.png)

**Comment by shorowit** [comment]
I can reproduce this bug by creating an arbitrary floorplan, saving, reopening, and clicking + Space

**Comment by shorowit** [comment]
I can't reproduce anymore. Seems like it's working.
