### ISSUE TITLE
Spaces disappear when selecting them

### ISSUE THREAD

**Issue by shorowit** [NatLabRockies/floorspace.js#121]
Using the latest code from the undo/redo branch.

Rename video file to *.webm
[Aug 3 2017 12-19 PM.webm.txt](https://github.com/NREL/openstudio-geometry-editor/files/1198211/Aug.3.2017.12-19.PM.webm.txt)

**Comment by bgschiller** [comment]
@shorowit It looks like this is not happening for me on develop. Do you mind checking if it's still broken for you? 

What I'm seeing: https://trello-attachments.s3.amazonaws.com/58d428743111af1d0a20cf28/5997142a0cfdf96f330263c7/f7914b900c5a085f802dba821f8b7399/recording.webm

**Comment by shorowit** [comment]
I was able to reproduce it using develop ffb5fc1304cd847e0902202628076f6372a93e66. By the way, undo/redo is **awesome** for being able to reproduce the issue and show the steps:

![image](https://user-images.githubusercontent.com/5861765/29468356-1a3eb1dc-8401-11e7-9e1b-828eb57b3ba1.png)

![image](https://user-images.githubusercontent.com/5861765/29468358-21e5e1c6-8401-11e7-9677-a966298c2e25.png)

![image](https://user-images.githubusercontent.com/5861765/29468369-292f4f6c-8401-11e7-9e18-57cda27a2161.png)

![image](https://user-images.githubusercontent.com/5861765/29468383-35d85a56-8401-11e7-937a-8f87d554683a.png)

**Comment by shorowit** [comment]
Tried the latest develop but I can't perform the same sequence of actions because I get an error:
![image](https://user-images.githubusercontent.com/5861765/29468731-b36aafb8-8402-11e7-8df2-11f7ad77bf90.png)

**Comment by bgschiller** [comment]
I just pushed a fix for this to develop, so I'm marking this 'needs verify'.

**Comment by shorowit** [comment]
Works for me now.
