### ISSUE TITLE
Disable controls when Quick Start is visible

### ISSUE THREAD

**Issue by shorowit** [NatLabRockies/floorspace.js#123]
Currently you can interact with all of the controls in the background (map, + space, etc etc) when the Quick Start "popup" is visible. Minor issue though.

**Comment by bgschiller** [comment]
some work done in `overlay-prevent-button-click-123`, but not finished yet.

**Comment by bgschiller** [comment]
Spent about 3 hours on this today. Learned some things, but I'm not much closer to a solution.

**Comment by shorowit** [comment]
This is not yet in develop, right?

**Comment by bgschiller** [comment]
@shorowit is it not working for you? It's in develop as of 23 minutes ago: https://github.com/NREL/openstudio-geometry-editor/pull/205

**Comment by shorowit** [comment]
https://github.com/NREL/openstudio-geometry-editor/commit/849389d36366d7a4f903176568b7a493815aa074 Perfect, thanks.
