### ISSUE TITLE
window.api.importLibrary missing

### ISSUE THREAD

**Issue by macumber** [NatLabRockies/floorspace.js#125]
@devKate knows about this, just a reminder

**Comment by macumber** [comment]
Thanks @devKate the method is there now, but I'm having trouble calling it:

```
window.api.setConfig();
window.api.init();
window.api.importLibrary(JSON.stringify({"project":{"config": {"units": "ft","language": "en-us"} },"building_units":[],"construction_sets":[],"space_types":[{"handle":"{65ea0937-98ea-42cb-a8d2-696c300318fe}","id":null,"name":"Space Type 1"}],"stories":[],"thermal_zones":[], "windows":[], "daylighting_controls":[]}));
```

It appears at the stories element is causing issues.  I would like to be able to import library items from any floorplan.json file.  Can we make import simply ignore the stories element in the import library routine?  Additionally, we need to add building_units and thermal_zones to the importable objects

**Comment by macumber** [comment]
Any floorplan.json conforming to the geometry_schema.json should be able to be imported as a library.  However, only a subset of the content will be imported in importLibrary.  

Application and project elements will be checked for compatibility with the current library and we may support unit conversion on import in the future, however the current model's application and project elements will not be affected by importLibrary.

The stories element will not be referenced during importLibrary, no geometry will be imported. 

All other elements (building_units, thermal_zones, space_types, construction_sets, windows, and daylighting_controls) will be imported, merging with the current library.  All imported objects should be given new ids on import, they should not be matched up with existing objects by id.  If an imported object has the same name as an existing object of the same type, the imported object should be renamed.

**Comment by gh-23378** [comment]
Could you elaborate on "Application and project elements will be checked for compatibility with the current library"?

**Comment by macumber** [comment]
Main thing is if you are importing a library in meters into a project in ft, eventually we might need to do unit conversion (if windows remain as library items).  

I can't think of any other checks, but there might be some.  Big thing is that the current project's application and project elements are not altered during a library import.

**Comment by macumber** [comment]
I put changes to the schema to support this https://github.com/NREL/openstudio-geometry-editor/commit/d0a68d1c79c4edafc309b40abf59f1b71894c786

**Comment by macumber** [comment]
I believe this is closed, @devKate ?
