### ISSUE TITLE
Can't import valid floorplan (according to schema)

### ISSUE THREAD

**Issue by macumber** [NatLabRockies/floorspace.js#126]
The following JSON validates against the schema but generates this error on import.  Either we should fix the code to treat the missing properties as optional or we should update the schema to make these properties required:

```
TypeError: Cannot read property 'spaces' of undefined
    at r (embeddable_geometry_editor.html:121)
    at Array.<anonymous> (embeddable_geometry_editor.html:27)
    at I.dispatch (embeddable_geometry_editor.html:27)
    at I.dispatch (embeddable_geometry_editor.html:27)
    at I.e.dispatch (embeddable_geometry_editor.html:121)
    at Object.doImport (embeddable_geometry_editor.html:131)
    at <anonymous>:1:12
```

**Comment by macumber** [comment]
`{"application":{"currentSelections":{"building_unit":null,"image":null,"mode":"spaces","shading":null,"space":{"building_unit_id":null,"color":"#007373","construction_set_id":null,"daylighting_controls":[],"face_id":"12","handle":null,"id":"3","name":"Space 1 - 1","space_type_id":null,"thermal_zone_id":null,"type":"space"},"space_type":null,"story":{"below_floor_plenum_height":0,"floor_to_ceiling_height":0,"geometry_id":"2","handle":null,"id":"1","images":[],"multiplier":0,"name":"Story 1","shading":[],"spaces":[{"building_unit_id":null,"color":"#007373","construction_set_id":null,"daylighting_controls":[],"face_id":"12","handle":null,"id":"3","name":"Space 1 - 1","space_type_id":null,"thermal_zone_id":null,"type":"space"}],"windows":[]},"thermal_zone":null,"tool":"Rectangle"},"modes":["spaces","shading","building_units","thermal_zones","space_types","images"],"scale":{},"tools":["Pan","Drag","Rectangle","Polygon","Eraser","Select","Map","Fill"]},"building_units":[],"construction_sets":[],"daylighting_controls":[],"project":{"config":{"language":"EN-US","north_axis":0,"units":"m"},"grid":{"spacing":50,"visible":true},"map":{"elevation":0,"enabled":true,"initialized":true,"latitude":39.765300000000003,"longitude":-104.9863,"rotation":0,"visible":true,"zoom":4.5},"previous_story":{"visible":true},"view":{"max_x":500,"max_y":194.06196213425127,"min_x":-500,"min_y":-194.06196213425125}},"space_types":[{"handle":"{65ea0937-98ea-42cb-a8d2-696c300318fe}","id":"","name":"Space Type 1"}],"stories":[],"thermal_zones":[],"windows":[]}
`

**Comment by macumber** [comment]
@devKate I'm happy to make changes to the schema if you want me to

**Comment by macumber** [comment]
I made additional schema changes here, https://github.com/NREL/openstudio-geometry-editor/pull/156

@devKate if you can evaluate this pull request (basically making name required for all objects with a name) then I think this ticket is done

**Comment by macumber** [comment]
If validation rules are required for the editor to ensure required and unique names for each object then that should be included as well (I thought we already had this?)

**Comment by gh-23378** [comment]
Validation in the library prevents duplicate names
