### ISSUE TITLE
Can't click space vertex inside another space

### ISSUE THREAD

**Issue by shorowit** [NatLabRockies/floorspace.js#129]
Seems like a regression in develop. This definitely worked at one point.

Draw a space:
![image](https://user-images.githubusercontent.com/5861765/29375222-77d0dc94-8271-11e7-87a4-96d65630cc1d.png)

Create a new space and try to end it by clicking inside the first space. The tool doesn't seem to register the click:
![image](https://user-images.githubusercontent.com/5861765/29375251-8f8cab38-8271-11e7-8cde-50d1e23c44b3.png)

**Comment by bgschiller** [comment]
@shorowit Strange, This is working for me on develop: https://trello-attachments.s3.amazonaws.com/58d428743111af1d0a20cf28/5995d380347c831a177ea7d0/b2359f93d092e5aaabc7df28ec5b205c/recording.webm

Any other advice for reproducing it?

**Comment by shorowit** [comment]
Oops, I think I was using the undo-redo branch. Sorry for the distraction.

**Comment by bgschiller** [comment]
ah, no worries :)
