### ISSUE TITLE
spacetypes incorrectly deleted

### ISSUE THREAD

**Issue by shorowit** [NatLabRockies/floorspace.js#131]
Open this floorplan json file:
[residential_template.json.txt](https://github.com/NREL/openstudio-geometry-editor/files/1229181/residential_template.json.txt)

Note that there are 5 spacetypes displayed in the interface.

Switch the navigation dropdown to `Thermal Zone` and create two thermal zones. Then delete the second one.

Bug: there are now four spacetypes.

**Comment by bgschiller** [comment]
fixed in #146
