### ISSUE TITLE
Various small UI improvements

### ISSUE THREAD

**Issue by shorowit** [NatLabRockies/floorspace.js#135]
- [x] Add a "Save As" dialog when the user clicks Save Floorplan
- [x] Use a thicker highlight border for the selected tool (e.g., "Rectangle")
- [x] Remove highlight border from the Open Floorplan and Save Floorplan buttons. 
- [x] Fix the horizontal spacing between the Import Library, Open Floorplan, and Save Floorplan buttons
- [x] When a space is selected in the navigator, scroll to it in the library pane to make it visible (if spaces are being currently displayed in the library, of course). Same for other objects (zones, spacetypes, etc.).
- [x]  Allow expanding/collapsing the library pane.

**Comment by bgschiller** [comment]
All but the last are done in `ui-improvements-135`. @devKate, you said you wanted to tackle that last one?

**Comment by shorowit** [comment]
I recommend merging the branch without the resizing item, which sounds like it's not so simple. That can be deferred.

**Comment by macumber** [comment]
Sounds good to me
