### ISSUE TITLE
Spaces don't show up when loading old floorplan.json

### ISSUE THREAD

**Issue by ljbrackney** [NatLabRockies/floorspace.js#138]
Using fresh develop build from late PM on 8/16.  Open an old floorplan.json that worked fine before.

[floorplan.json.zip](https://github.com/NREL/openstudio-geometry-editor/files/1229778/floorplan.json.zip)

I see this.  Right geolocation, but no content.  Changing type in navigator pane doesn't do anything - always stuck with +Space as an option.
![geom1](https://user-images.githubusercontent.com/2230150/29390149-6b744094-82a3-11e7-9990-a1e5ab57f43f.png)
Add a floor.  Still no apparent change.
![geom2](https://user-images.githubusercontent.com/2230150/29390187-a20e1f12-82a3-11e7-9797-971200580586.png)
Change type in navigator pane and wham!  Content!
![geom3](https://user-images.githubusercontent.com/2230150/29390208-b9551644-82a3-11e7-9c31-43501760d093.png)
Delete extraneous floor, switch back to Space type, and things are where they should have been when I first opened the floorplan.json...
![geom4](https://user-images.githubusercontent.com/2230150/29390236-db73dfb2-82a3-11e7-9031-61cc3678642b.png)

**Comment by macumber** [comment]
I tested with current develop and this appears to be fixed, assigning back to @ljbrackney to test at a later date (to make sure it stays fixed)
