### ISSUE TITLE
Image doesn't immediately display after open floorplan

### ISSUE THREAD

**Issue by shorowit** [NatLabRockies/floorspace.js#142]
Open this floorplan:
[test.json.txt](https://github.com/NREL/openstudio-geometry-editor/files/1232468/test.json.txt)

You should see this:
![image](https://user-images.githubusercontent.com/5861765/29431529-7e697b44-8355-11e7-8157-a8d5d4558df0.png)

If you switch to story 2 and then back to story 1, the image on story 1 now appears:
![image](https://user-images.githubusercontent.com/5861765/29431546-8e064fbe-8355-11e7-97cc-a45171b6d38b.png)

**Comment by gh-23378** [comment]
Having trouble reproducing this with any new floorplans.

**Comment by shorowit** [comment]
Steps that allow me to reproduce. It actually looks like it's less that the image doesn't immediately appear and more that it's size/position is initially incorrect.

New floorplan, zoom out, draw space:
![image](https://user-images.githubusercontent.com/5861765/29435183-3ca23698-8363-11e7-88a6-20dbf170c520.png)

Add story, switch to Image in Navigator, +Image, choose floorplan.jpg:
![image](https://user-images.githubusercontent.com/5861765/29435205-5095f4aa-8363-11e7-87b6-2c270befdad8.png)

Click Drag, drag image around:
![image](https://user-images.githubusercontent.com/5861765/29435216-5d4216d4-8363-11e7-8799-d649e94a40da.png)

Switch to story 1, +Image, choose floorplan2.jpg, drag around:
![image](https://user-images.githubusercontent.com/5861765/29435247-72a752be-8363-11e7-923f-0f596c675e01.png)

Switch to story 2. Save floorplan. Reopen floorplan. Note that image is incorrectly sized/positioned (BUG):
![image](https://user-images.githubusercontent.com/5861765/29435278-99a7cbaa-8363-11e7-82e9-30d2bbf6b9c3.png)

Switch to story 1 and then back to story 2. Image is now fixed:
![image](https://user-images.githubusercontent.com/5861765/29435293-b0d11110-8363-11e7-93a9-392adc15c67b.png)

**Comment by ljbrackney** [comment]
Sounds like a number of this issues I noted here:

https://github.com/NREL/openstudio-geometry-editor/issues/82

**Comment by shorowit** [comment]
Hmm, I went through the same steps as before and see the same bug.

**Comment by shorowit** [comment]
Weird, maybe I wasn't using the latest version? It's working for me now.
