### ISSUE TITLE
Combine Image Pan & Drag

### ISSUE THREAD

**Issue by shorowit** [NatLabRockies/floorspace.js#144]
Currently there are separate Pan and Drag tools for images. I suggest we combine the tools such that:
- If you click while over an image and move your mouse, the image is dragged
- If you click while not over an image and move your mouse, the drawing area is panned

This would have a similar feel to the Rectangle tool where you can draw new space rectangles and pan the drawing area with the single tool selected.

**Comment by bgschiller** [comment]
@devKate I started working on this, but it looks like it can't be done as long as we're rendering images in a canvas. Would you be opposed to rendering the images *inside* the svg.

The issue is that either the canvas or the svg can accept pointer-events, but not both at the same time.

**Comment by shorowit** [comment]
This seems implemented in develop. Right, @bgschiller ?

**Comment by bgschiller** [comment]
Yes, that's right. 🎉
