### ISSUE TITLE
Error when erasing

### ISSUE THREAD

**Issue by shorowit** [NatLabRockies/floorspace.js#149]
Video to reproduce:
[Aug 18 2017 4-25 PM.webm.txt](https://github.com/NREL/openstudio-geometry-editor/files/1235779/Aug.18.2017.4-25.PM.webm.txt)

**Comment by bgschiller** [comment]
@shorowit Seems to be working for me. https://trello-attachments.s3.amazonaws.com/58d428743111af1d0a20cf28/599de7494fabed498c11fb6b/7afe282dd3d2b54c0707104b6ec60cf2/recording.webm

Likely fixed by https://github.com/NREL/openstudio-geometry-editor/pull/148

**Comment by shorowit** [comment]
Yep, works now.
