### ISSUE TITLE
Adding floors and spaces isn't working correctly

### ISSUE THREAD

**Issue by ljbrackney** [NatLabRockies/floorspace.js#152]
Clicking Add Floors or Add Spaces doesn't appear to do anything.

![added](https://user-images.githubusercontent.com/2230150/29496138-738ead92-8581-11e7-8e32-0830f26ab7d1.png)

Until you hit refresh or merge then you see this:

![floors](https://user-images.githubusercontent.com/2230150/29496147-8e0fafc2-8581-11e7-8550-5f9b41def125.png)

Adding Spaces isn't working reliably, and note that existing geometry isn't showing up at all per my comment in https://github.com/NREL/openstudio-geometry-editor/issues/150.  (This is the same two space model.)

**Comment by macumber** [comment]
This might be an error with the floorplan.json that is crashing the editor.  Connecting with the chrome debugger might help.

**Comment by macumber** [comment]
Might be related to https://github.com/NREL/openstudio-geometry-editor/issues/151

**Comment by macumber** [comment]
I think this is a duplicate of #151
