### ISSUE TITLE
Spaces drawn when viewing zones

### ISSUE THREAD

**Issue by shorowit** [NatLabRockies/floorspace.js#162]
1. New floorplan.
2. Switch to Thermal Zone in the Navigator.
3. Try drawing -- it will start drawing a rectangle for Space 1 - 1 even though Thermal Zones are displayed.
4. Even if you create a thermal zone, which causes Thermal Zone 1 to be selected, it will continue to allow drawing a rectangle for Space 1 - 1.

Presumably occurs because we don't have any action tool buttons defined for Thermal Zone yet.

**Comment by bgschiller** [comment]
Sounds like we might get rid of Thermal Zone in the navigator in the future, so may not be an issue.

**Comment by shorowit** [comment]
No longer applies.
