### ISSUE TITLE
Grid lines don't line up with grid points

### ISSUE THREAD

**Issue by macumber** [NatLabRockies/floorspace.js#174]
When using strict grid mode, I seem to be snapping to grid points that do not correspond to the visible grid lines.

Probably related to https://github.com/NREL/openstudio-geometry-editor/issues/132

**Comment by macumber** [comment]
![image](https://user-images.githubusercontent.com/1327850/29632249-a740bda8-87ff-11e7-9356-4807542e051b.png)

**Comment by shorowit** [comment]
I have not seen this behavior in a while.
