### ISSUE TITLE
Copy objects

### ISSUE THREAD

**Issue by shorowit** [NatLabRockies/floorspace.js#178]
There are various objects (like stories and spaces) where you might like a copy capability that preserves their properties. For stories, you might like to preserve the height. For spaces, you might like to preserve thermal zone, space type, construction set, etc. There may be additional objects worth copying, just adding this as a placeholder for now.

Adapted from https://github.com/NREL/OpenStudio/issues/2740#issuecomment-324476130.

**Comment by macumber** [comment]
I like this feature, my only question is how to implement it in the ui?  Would this just be a 'x2' button next to delete?

**Comment by macumber** [comment]
Also if you copy it, I would suggest incrementing the name:

"Space 1" - > "Space 1 Copy" -> Space 1 Copy 1" -> Space 1 Copy 2"

**Comment by shorowit** [comment]
This is awesome! I did a bit of testing and it's working well. 

I'd prefer that we use shorter names though since they currently don't fit sometimes:

![image](https://user-images.githubusercontent.com/5861765/39645211-bef8f9b2-4f94-11e8-9b66-c7744e7d0ec2.png)

Maybe we can simply do "Space 1" -> "Space 1 (2)" -> "Space 1 (3)"?

**Comment by shorowit** [comment]
Nice.

**Comment by DavidGoldwasser** [comment]
@macumber @shorowit At one point we talked about duplicating a story where spaces would be duplicated with the story. Is that something anyone else had an interest in? Currently the story properties are copied, but not the spaces that are on the story. Use case was maybe a 5 story multifamily building where stories are similar but not exactly the same. Was going to copy stories and then modify. Could probably do this in script outside of the GUI, but thought I'd see if it was planned as a feature. I didn't see an issue for it.

**Comment by bgschiller** [comment]
We've implemented that functionality for Speed's fork of floorspace.js, and it wasn't too difficult to do. Maybe we should just change the behavior of "Copy story" to do as @DavidGoldwasser suggests?

**Comment by DavidGoldwasser** [comment]
Just reopening this so it is on the radar. I had a use case for this I used a work around for, but would be good to have in the future. cc @macumber

**Comment by Mkellyeng** [comment]
As a user, this would be a useful feature

**Comment by kylem038** [comment]
Just merged in the code for this. Let us know if there's anything else needed here, but going to close this for now.
