### ISSUE TITLE
Would like new floors to duplicate height settings from previous floors

### ISSUE THREAD

**Issue by ljbrackney** [NatLabRockies/floorspace.js#179]
It would be a great convenience if new floors duplicated the floor-ceiling and plenum entries from the previous floor.  Also is it possible to default those fields to something "reasonable?"  Like a 10 ft floor-ceiling with 0 plenums?

**Comment by shorowit** [comment]
The first part of this request could be related to the Copy Objects feature request (https://github.com/NREL/openstudio-geometry-editor/issues/178).

**Comment by bgschiller** [comment]
I'm reading this ticket as "When a new story is created, copy the values from the previous story". However, @shorowit also mentions #178, which would do that same thing using a more explicit user action. Perhaps this ticket should be closed in favor of that?

Or maybe the answer here is to change some defaults. The defaults can be changed by modifying geometry_schema.json. Are there changes I should make to that?

**Comment by macumber** [comment]
I think you are right, copy function should copy the values, while add new button should pull from the schema.

**Comment by bgschiller** [comment]
Great. I recommend closing this issue then, unless you have thoughts on what we should change the defaults to, as @ljbrackney suggests.

**Comment by shorowit** [comment]
We updated a number of defaults previously, I think this is good to go.
