### ISSUE TITLE
The Preview (next to merge) isn't fully functional

### ISSUE THREAD

**Issue by DavidGoldwasser** [NatLabRockies/floorspace.js#181]
The "Render By" and "Show Story" pull down choices can't be selected.

These do work in the "Preview" tab in OS app 2.1.1.

**Comment by macumber** [comment]
I've noticed this too, you should be able to open the drop down then navigate with arrow keys.  Also this issue should be in the OpenStudio repo since it is an integration thing

**Comment by macumber** [comment]
Moved to https://github.com/NREL/OpenStudio/issues/2753

**Comment by DavidGoldwasser** [comment]
@macumber NREL/OpenStudio#2753 is about the preview tab, this bug is before you get to the preview tab, in the pre-merge preview. Just wanted to clarify.
