### ISSUE TITLE
"Make New Zone" in thermal zone assignment pulldown

### ISSUE THREAD

**Issue by DavidGoldwasser** [NatLabRockies/floorspace.js#182]
Often there will be a one to one mapping of space to thermal zones. It would be nice to have an option in thermal zone list to "Make New Zone". For now I just left zones empty, then when to zone view, then made a lot of thermal zones, then went back to re-assign them.

This feature could name the "New Thermal Zone" based on the space name. Sure this could be done in Apply Measures Now outside of editor, but would be nice to have here.

**Comment by shorowit** [comment]
If I understand correctly, you'd like the thermal zone dropdown for spaces in the library pane to include, e.g., a "New" or "+" option? 

![image](https://user-images.githubusercontent.com/5861765/29684190-5205e104-88ce-11e7-9086-cdf66d5a86c5.png)

Seems like all of the dropdowns (building unit, spacetype, etc.) could have this. Ideally you'd at least get asked for a name (perhaps defaulting to the space name, like you suggest).

**Comment by DavidGoldwasser** [comment]
@shorowit yes, that is what I was thinking. I agree, would be nice for all objets, but I was most interested in it for thermal zones which are not a resource that I would be likely to pre-load in my model.

This approach is taken in the SketchUp Plugin Space Attributes tool that let you pick an existing attribute or make a new one on the fly.

**Comment by shorowit** [comment]
For residential, we will often have pre-loaded thermal zones. I'm sure we can figure out the right functionality to make it work for all use cases.

**Comment by macumber** [comment]
Marj is working on some new mockups that probably address this

**Comment by LyleKeck** [comment]
It would be nice to have an option to 'Create new ThermalZone for each space' (automatically) similar to the SketchUp Plugin option under preferences.  [tested using OS 2.2.2]
