### ISSUE TITLE
Lockup on "+ Image"

### ISSUE THREAD

**Issue by DavidGoldwasser** [NatLabRockies/floorspace.js#186]
Window comes up to browse for file, but then app freezes before I do anything (I have not browsed yet or selected an image).

I'm seeing this through OS app, I noticed in issue #143 @shorowit was able to add images in, So maybe what I'm seeing is now, or unique to use in OS app?

I was able to repeat this on new project.

**Comment by shorowit** [comment]
Just tried it. It worked for me in the OS app on Windows 10.

**Comment by ljbrackney** [comment]
I suspect this is an issue w/ how the file browser is being invoked from the editor - sounds like the same issue I opened for importing a floorplan.

**Comment by macumber** [comment]
Might be a mac only thing?

**Comment by macumber** [comment]
@DavidGoldwasser if you can't reproduce using the standalone_geometry_editor.html (have to load in chrome) at https://github.com/NREL/openstudio-geometry-editor/releases/tag/v0.2.2 then we should move this to OpenStudio issues

**Comment by ljbrackney** [comment]
I think this is an app integration issue, and not specific to the editor itself.  I've never had trouble with the file dialogs working standalone.

**Comment by macumber** [comment]
I am seeing this on Windows too in the app

**Comment by macumber** [comment]
Moved to https://github.com/NREL/OpenStudio/issues/2754
