### ISSUE TITLE
Issue drawing simple case

### ISSUE THREAD

**Issue by macumber** [NatLabRockies/floorspace.js#191]
Start the editor, create new floorplan with map, rotate to align with building, set grid spacing to 15ft.  Draw space 1:

![image](https://user-images.githubusercontent.com/1327850/29733253-8434379e-89a9-11e7-84d7-d5ab175f1a98.png)

Extend space 1:
![image](https://user-images.githubusercontent.com/1327850/29733258-8c2fc396-89a9-11e7-9f91-a499f2370e39.png)

Create space 2 and attempt to draw:
![image](https://user-images.githubusercontent.com/1327850/29733271-9a3b9744-89a9-11e7-97e5-fea469c8f77b.png)

Space 1 geometry gets corrupted:
![image](https://user-images.githubusercontent.com/1327850/29733280-a73bf204-89a9-11e7-8f76-2e5ca269be3b.png)

At this point the editor is fairly broken

**Comment by macumber** [comment]
Noticed that North Axis is set to 0 even though the map was rotated, saw same message about unknown local mutation type for setNorthAxis as reported in https://github.com/NREL/openstudio-geometry-editor/issues/180

**Comment by bgschiller** [comment]
@macumber Is this still happening for you? I've made a number of fixes, and can't reproduce this on develop.
