### ISSUE TITLE
Place daylighting controls

### ISSUE THREAD

**Issue by shorowit** [NatLabRockies/floorspace.js#210]

**Comment by macumber** [comment]
The vertex referenced by a daylighting control point should not be shared, i am going to update the schema to just include x and y in the control point

**Comment by macumber** [comment]
When a daylighting control point is placed it must be inside a space (it is a child of that space). 

If the space is deleted, the control point is deleted.

If a space is resized, any control points outside the space are deleted

If a space is moved, all daylighting control points in it are moved by the same amount and in the same direction

**Comment by macumber** [comment]
https://github.com/NREL/openstudio-geometry-editor/commit/62da5a2bf6958dbe3a5ceae42419c1a72f26c465

**Comment by shorowit** [comment]
A few bugs/questions:
1. A daylighting control can sometimes move after it's been placed. Example video:
[Sep 27 2017 9-41 AM.webm.txt](https://github.com/NREL/openstudio-geometry-editor/files/1337801/Sep.27.2017.9-41.AM.webm.txt)
2. I sometimes see the finalized daylighting control one grid cell off from where it was displayed when I clicked the mouse to place it.  Example video:
[Sep 27 2017 10-44 AM.webm.txt](https://github.com/NREL/openstudio-geometry-editor/files/1338014/Sep.27.2017.10-44.AM.webm.txt)
3. If you've placed a daylighting control in one space and then draw over with another space, should the daylighting control be preserved (and reassigned to the new space)? Similar question for windows.

**Comment by shorowit** [comment]
This is all working as I expect.
