### ISSUE TITLE
Image import file types

### ISSUE THREAD

**Issue by macumber** [NatLabRockies/floorspace.js#216]
Image import feature should restrict dialog to supported file types.  If user selects a file that cannot be imported as an image, an error message should be shown.

**Comment by bgschiller** [comment]
@macumber Is that not already the case for you? This is what I see when I try to choose an image other than a jpeg, png, or gif:
https://trello-attachments.s3.amazonaws.com/58d428743111af1d0a20cf28/5ae8a16eb52300bacf060e82/55e547b3bd48a10a1abf68ed0f02f5bd/recording.webm

**Comment by macumber** [comment]
It looks like it is working :-)
