### ISSUE TITLE
Component Refinements

### ISSUE THREAD

**Issue by bgschiller** [NatLabRockies/floorspace.js#218]
- [x] round the x/y coordinates 'Daylighting control created at (x, y)"
- [x] give daylighting controls "cursor-events: none;"
> if you are hovering your mouse to place a daylighting control and click with your mouse on the yellow portions of the icon (top-left or bottom-right wedges), the control is not created. but if you click on the transparent portions of the icon (top-right or bottom-left), it works.
- [x] relocating daylighting events when a space is draw over them https://nrel-geometry-editor.slack.com/files/U4RHTMLS1/F74RZE11A/sep_18_2017_9-57_am.webm
- [x] disappearing windows: https://nrel-geometry-editor.slack.com/files/U4RHTMLS1/F74UBBUJH/sep_18_2017_9-53_am.webm
- [x] Add window guideline showing distance to start of edge.
- [x] Snap windows to multiples-of-spacing distances along the edge.
- [x] Add daylighting guideline showing distance (and perp, parallel components of distance) to the center of the closest window (or edge, if no window).

**Comment by shorowit** [comment]
Looks good to me.
