### ISSUE TITLE
Keep space coordinates when drawing space and zooming

### ISSUE THREAD

**Issue by LyleKeck** [NatLabRockies/floorspace.js#224]
When drawing a space, it would be nice not to lose the space when zooming in or out.  Currently if you start drawing a space and then re-scale the grid using the mouse scroll wheel, the space you were drawing disappears. [Tested in OS 2.2.2]

**Comment by shorowit** [comment]
Agreed. Along the same lines, it would be nice if you could pan the drawing area while drawing a space. This might prevent the situation of having to zoom out while drawing a space. 

Here's an example of how that worked in BEopt:
[Sep 28 2017 4-03 PM.webm.txt](https://github.com/NREL/openstudio-geometry-editor/files/1342502/Sep.28.2017.4-03.PM.webm.txt)

**Comment by ljbrackney** [comment]
+1!

**Comment by shorowit** [comment]
This is working really well in the latest develop. You can pan and zoom without losing the space that you're actively drawing.
