### ISSUE TITLE
Property defaults/constraints/units

### ISSUE THREAD

**Issue by shorowit** [NatLabRockies/floorspace.js#228]
Many object properties default to 0 or null, whereas they really should be > 0. I suggest we use values from the first example object in the default_library.json. So:

Window Definition:

- Height: 4
- Width: 2
- Sill Height: 3

Daylighting Control:

- Height: 3
- Illuminance Setpoint: 300

Pitched Roof:

- Type: Gable
- Pitch: 6

For Story, I recommend:

- Floor to Ceiling Height: 8 (Dan might want a larger value for commercial?)
- Multiplier: 1

Here is the list of properties that the editor should not allow to be <= 0:

- Window Definition: Height, Width, Sill Height
- Daylighting Control Defintion: Height, Illuminance Setpoint
- Pitched Roof: Pitch
- Story: Floor to Ceiling Height, Multiplier

I also noticed that new Pitched Roof objects are not being assigned a new color, as is the case for stories, thermal zones, etc.

Finally, we should really label units for the properties. For example:

- "Height" -> "Height [ft]"
- "Illuminance Setpoint" -> "Illuminance Setpoint [lux]"

**Comment by shorowit** [comment]
The defaults should probably also be in the schema, according to @macumber.

**Comment by bgschiller** [comment]
Read these from the Schema
