### ISSUE TITLE
New UI initial feedback

### ISSUE THREAD

**Issue by shorowit** [NatLabRockies/floorspace.js#233]
The UI is a **huge** step forward in terms of usability! Great work. Here's my list of random stuff that I found while playing with the latest develop.

- [x] I find it confusing that there is a Spaces list displayed on the left (with which you can select spaces) when you are on the Assign tab. The Components tab is more confusing in this respect as, e.g., Windows instances show up for selection, but this is not the way to create a new window. We should discuss possible solutions here. 
- [x] Quickstart dialog: change "New Floorplan w/ Map" to "Create a new floorplan with a map" for consistency. I'd also reorder the items so that Open is third.
- [x] When you use alt-+shift to rotate the map, the north axis arrow doesn't rotate with the map; when you click "Done", then the arrow updates. Ideally the arrow would update while you rotate, though you could also simply hide the arrow until Done is clicked.
- [x] When you draw a space and then change the "View By" dropdown, there's no way to get back to the original state where the space color is displayed. I also don't know what the "--" (or the blank default) is supposed to mean.
![image](https://user-images.githubusercontent.com/5861765/31910985-76dbfbd2-b7fc-11e7-9868-13cb4fda5d9e.png)
- [x] It's great to see tooltips for some of the buttons (like Rectangle)! Please add tooltips to the open/save/import/undo/redo buttons too.
- [x] Depending on browser size, when you expand the spaces list to see their details, that pane can be wider than the viewable area with no way to horizontally scroll to see the properties off the screen.
![image](https://user-images.githubusercontent.com/5861765/31911021-905d7054-b7fc-11e7-8322-d37de06b9339.png)
- [x] If you click zoom-to-fit with no spaces drawn, there is an error.
- [x] Zoom to fit currently operates on the current story. If there are outlines of spaces from the story below, they are not taken into account. Either the algorithm should take them into account (if the checkbox is enabled) or zoom to fit should simply be applied to the entire building (all stories). The latter could be nice so that you could zoom-to-fit on any story and then switch stories and know that you'll see everything.
- [x] Is it possible to hide the Story/Space pane vertical scrollbars when not needed?
![image](https://user-images.githubusercontent.com/5861765/31911066-b31d31e2-b7fc-11e7-8b6f-93697dec2b62.png)
- [x] When I click on one of the Assign buttons (like Building Unit), I sometimes see multiple horizontal and/or vertical scrollbars. Also, the header doesn't stay fixed when you scroll down.
![image](https://user-images.githubusercontent.com/5861765/31911207-226e0472-b7fd-11e7-9a3e-e12d3641f1e2.png)
- [x] When I switch from a Window selected to a Daylighting Control selected, the left-hand pane continues to show Window instances unless I manually change it. I would think it should sync?
- [x] The "Total Count" for, e.g., Windows should be right-justified for consistency with the other fields. In the image below, it looks like the Sill Height is 32, whereas the Sill Height is 3 and the Total Count is 2.
![image](https://user-images.githubusercontent.com/5861765/31911493-17207d42-b7fe-11e7-9234-e0c7e23b2a07.png)
- [x] I find the logic that sometimes changes the displayed grid relative to the actual grid (when zoomed out a lot) to be very confusing. For example, if I simply open the app and change the grid size from 5ft to 1ft, I get very large grid cells (whereas I expect smaller grid cells) that I eventually understand are 50ft grid cells. 
![image](https://user-images.githubusercontent.com/5861765/31911507-257c5d3e-b7fe-11e7-8981-8e32772e7ecd.png)
- [x] The floorplan buttons seems left they should be left-justified similar to the Assign/Components tabs.
![image](https://user-images.githubusercontent.com/5861765/31911651-9c74a0ae-b7fe-11e7-8831-7054c825dc1f.png)
- [x] Change the Assign text from "Add connections & Roof" to "Assign thermal zones, etc., to spaces."

**Comment by bgschiller** [comment]
@shorowit I finished most of these items. A couple seemed like they needed some more discussion. I'll add those below, as well as the items from slack. The ones that are checked off are available in the `ui-feedback-233` branch.

- [x] I find it confusing that there is a Spaces list displayed on the left (with which you can select spaces) when you are on the Assign tab. The Components tab is more confusing in this respect as, e.g., Windows instances show up for selection, but this is not the way to create a new window. We should discuss possible solutions here.
- [x] I find the logic that sometimes changes the displayed grid relative to the actual grid (when zoomed out a lot) to be very confusing. For example, if I simply open the app and change the grid size from 5ft to 1ft, I get very large grid cells (whereas I expect smaller grid cells) that I eventually understand are 50ft grid cells. ![](https://user-images.githubusercontent.com/5861765/31911507-257c5d3e-b7fe-11e7-8981-8e32772e7ecd.png)
- [ ] Consider removing the image tool, and using it implicitly when 'images' is selected in dropdown at left.
- [x] Which tools should be available in component mode? Place/Remove component? Place/Select Component, with delete key to remove?
- [x] With regard to the first item ("I find it confusing that there is a Spaces list displayed..."), I tend to feel like we should just hide the child pane in the Navigator for both Assign and Components tab. This should be easy to implement, and as far as I can tell, the only drawback is that you can no longer rename component instances (not a big deal?).

**Comment by shorowit** [comment]
Looking good, @bgschiller!

- [x] With regard to the first item ("I find it confusing that there is a Spaces list displayed..."), I tend to feel like we should just hide the child pane in the Navigator for both Assign and Components tab. This should be easy to implement, and as far as I can tell, the only drawback is that you can no longer rename component _instances_ (not a big deal?). cc @macumber

A couple other notes:
- [x] When I expand the story or spaces panes, I can still see the grid through the pane and can still draw spaces. I also can't collapse the panes and get stuck.
- [x] Rename the first Quickstart text to simply "Create a new floorplan"
- [x] Add tooltips to the following buttons: zoom to fit, the + buttons next to story & space, the >> and << pane buttons, and the x delete buttons
- [x] Move the zoom to fit button next to the View By dropdown.
- [x] Undo bug: 1) Switch to Image, add image, click elsewhere on grid to deselect. 2) Switch to Space, 3) Click undo many times -- the image will never disappear. I think `application/setCurrentSubselectionType` might need to be skipped from the undo/redo state?
- [x] Rename the "Assign" tab to "Space Assignments" (or just "Assignments" if there's a concern about horizontal space). The other tabs are nouns.
- [x] Can we get an icon for the new "Ground Properties" button? And an OK (or Close) button on the modal dialog?

**Comment by shorowit** [comment]
- [x] The "search" capability should skip any color code fields.
![image](https://user-images.githubusercontent.com/5861765/32232138-00145c20-be1d-11e7-8c5d-6f9b5b401c99.png)

**Comment by shorowit** [comment]
- [x] The View By dropdown is not available on the Components tab. Is this intentional, or accidentally caused by the Place/Remove buttons? (I still hold out hope that we can make the Place/Remove buttons go away and merge their capabilities :smile:)

**Comment by shorowit** [comment]
- [x] When clicking the + to create, e.g., a new building unit, the new object should immediately become selected in the list.

**Comment by shorowit** [comment]
- [x] It's not clear to the user which property fields are editable vs read only. Examples of read only fields are Total Count for window definitions objects and Spaces for story objects. Can we use a border highlight (like seen below) to indicate the editable fields? I guess we will need a different border highlight to indicate the _active_ editable field.
![image](https://user-images.githubusercontent.com/5861765/32233978-4deb8faa-be21-11e7-848a-bfca8eddc54c.png)
- [x] If you have the, e.g., the Window Definitions pane open and then expand, e.g., the Story pane, the two panes overlap. Should probably collapse the Window Definitions pane automatically.

**Comment by shorowit** [comment]
- [x] This applies to both Assign/Components tabs. If you have, e.g., a thermal zone selected and then click on the building unit toolbar button, 1) the thermal zone should be deselected, 2) the view by should immediately change to building unit, and 3) if there are thermal zone objects available, the first one in the list should be selected. I also wonder whether the thermal zone should be immediately deselected when you click on it again to collapse the pane...

**Comment by shorowit** [comment]
A few more issues:
- [x] The order of objects (spaces, stories) in expanded panes is reversed from the collapsed panes. For example:
![image](https://user-images.githubusercontent.com/5861765/32563447-8754fa9e-c46e-11e7-905a-b5432a4c5cea.png)
![image](https://user-images.githubusercontent.com/5861765/32563453-8a138aa2-c46e-11e7-84b9-84b853947271.png)
- [x] The space's Open to Below property is not being preserved
- [x] If you try to change colors for an object, the color picker is off the screen:
![image](https://user-images.githubusercontent.com/5861765/32563531-c4bedbb6-c46e-11e7-86d8-12f9640e211b.png)

**Comment by shorowit** [comment]
- [x] When opening an existing floorplan, it should default to the lowest story selected. It currently defaults to the highest story selected.

**Comment by shorowit** [comment]
- [x] When I expand the stories pane, all stories say there is 1 shading object even though I have no shading objects.

**Comment by shorowit** [comment]
- [ ] I still see double scrollbars sometimes. For example:
![image](https://user-images.githubusercontent.com/5861765/32564088-5306d5d0-c470-11e7-9eaa-62ff850efff3.png)

**Comment by shorowit** [comment]
- [x] When switching to another story and then coming back, the space that was last selected for the story should be preserved.

**Comment by shorowit** [comment]
- [x] When I create pitched roof objects, the dropdowns in the space pane show that a pitched roof object has been automatically assigned whereas it shows as unassigned on the Assignments tab. Also, there is no way to unassign using the space pane dropdown. I believe this applies to other space assignments too?

**Comment by shorowit** [comment]
A few items I noticed in the latest build:
- [x] My mouse clicks don't always seem to be registering when drawing spaces. This seems like a recent regression.
- [x] When you have, e.g., a window instance selected, clicking the X button to delete it does nothing.
- [x] Remove "Definition"/"Defn" from the Components navigator dropdown. This should also help make the >> button fit in the pane.
- [x] When you switch to Construction Set from the Components navigator dropdown, the View By dropdown doesn't update.
- [x] When you try to assign a Construction Set to a space, I get this error: `unrecognized space property type construction_sets`
- [x] Might as well hide the + Story button on the Assignments/Components modes, as you'll need to go to the Floorplan mode first anyway to create spaces on the story (with which to make an assignment or place a component).

**Comment by shorowit** [comment]
Nice work!

A few small bugs:
- [x] Create a new floorplan, change grid spacing to 1 ft, zoom in until you can see grid lines, draw a space, expand space navigator pane, then collapse it. Drawn space is no longer at the position it previously was (and often disappears off the screen).
- [x] When positioning, e.g., a window, but you decide to pan the drawing, the window artifact remains during the pan:
![image](https://user-images.githubusercontent.com/5861765/32811688-53592efa-c95e-11e7-97cb-b0e356d16335.png)
- [x] The >> button doesn't fit in the components navigator pane:
![image](https://user-images.githubusercontent.com/5861765/32811670-3e539af4-c95e-11e7-828d-576a359cd362.png)

**Comment by shorowit** [comment]
I think this giant ticket has probably outlived its usefulness. Awesome work, @bgschiller, things are looking good to me. 🥇 👍 💯
