### ISSUE TITLE
Default library units not respected

### ISSUE THREAD

**Issue by macumber** [NatLabRockies/floorspace.js#250]
The default library units are in ft, however if you start a project in meters they do not seem to be translated (it appears that the first window and first daylighting control point are used as defaults)

https://github.com/NREL/openstudio-geometry-editor/blob/develop/schema/default_library.json#L4

**Comment by macumber** [comment]
I am not actually sure if the roof pitch units change in SI?  @shorowit ?

**Comment by shorowit** [comment]
The roof pitch is a ratio so it is unit-less.

**Comment by macumber** [comment]
Cool, I thought it might have been in inches/foot or something like that
