### ISSUE TITLE
Face with extra vertices/edges

### ISSUE THREAD

**Issue by shorowit** [NatLabRockies/floorspace.js#253]
@bgschiller @macumber Here's my first example. 

[Nov 29 2017 12_14 PM.webm.txt](https://github.com/NREL/openstudio-geometry-editor/files/1515214/Nov.29.2017.12_14.PM.webm.txt)
[floorplan.json.txt](https://github.com/NREL/openstudio-geometry-editor/files/1515216/floorplan.json.txt)

The (x,y) vertices for face id 13 is:
(-10,10)
(20,10)
(20,45)
(20,45)
(20,80)
(-10,80)
(-140,80)
(-140,-40)
(-10,-40)
(-10,-10)
(-10,10)

Note the duplicate adjacent vertices of (20,45), and thus, the extra edge. The face should have 9 edges, not 10.

**Comment by shorowit** [comment]
There is still the "issue" where you can generate two edges in series with identical interior/exterior conditions, whereas you would like for them to be collapsed. The current behavior results in extra surfaces (which impacts simulation speed) as well as having to, e.g., place window WWR along more edges than you'd expect. It'd be nice to fix this.

**Comment by ljbrackney** [comment]
I can confirm this.  It tends to occur when you "extend" a space with an additional rectangle.  The two rectangles form additional exterior surfaces.  Here's an example in the "Cafeteria" space.

![segment2](https://user-images.githubusercontent.com/2230150/35058199-0a1eb0bc-fb6c-11e7-9444-0313fa375f6a.png)
![segment](https://user-images.githubusercontent.com/2230150/35058207-0e46ac44-fb6c-11e7-8af6-dc3cf86c88cd.png)

**Comment by macumber** [comment]
@ljbrackney still occuring on the most recent geometry-editor branch?

**Comment by macumber** [comment]
Sounds like this is still happening after the simplify code was added to OS translation.  I think it may be too much to do this in the translator, especially as joining these edges might change windows.  I wonder if this should be an editor feature instead?  Might need to be a user interactive tool?  Click on co-linear edges to join them?

**Comment by shorowit** [comment]
Yes, I was proposing the change to the editor. Seems like the editor should automatically retain windows in the same way it currently handles it. For example:
[FloorspaceJS.webm.txt](https://github.com/NREL/floorspace.js/files/1640198/FloorspaceJS.webm.txt)

**Comment by macumber** [comment]
This code from OpenStudio could be leveraged via emscripten, https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/utilities/geometry/Intersection.hpp#L101

Alternatively, we could implement a similar method in JavaScript

**Comment by bgschiller** [comment]
I have some code in this direction already: [https://github.com/NREL/floorspace.js/blob/develop/src/store/modules/geometry/mergeEdges.js](mergeEdges.js). That could be used for either an automated or user-driven tool for combining edges.

However, I wonder if this has already been (partly) taken care by #322, where I found and fixed few cases that were creating exterior walls that should have been interior.

**Comment by DavidGoldwasser** [comment]
Just wanted to extend this with example where wall being un-expectedly split by extra vertices is impact how window application occurs. What should be one wall, is two, and results in different window layout which has to avoid straddling the split.

<img width="870" alt="floorspaceJS_issuse1" src="https://user-images.githubusercontent.com/4857055/97205573-44598380-177d-11eb-8694-c1d2c7d0738b.PNG">
<img width="756" alt="floorspaceJS_issuse2" src="https://user-images.githubusercontent.com/4857055/97205586-46bbdd80-177d-11eb-9d0f-61381706d080.PNG">

**Comment by bgschiller** [comment]
Related to #350

**Comment by kylem038** [comment]
@DavidGoldwasser I'm going to look a bit more into this. I know it's a long shot but is there any chance you have a floorplan I could import that showcases this issue?

**Comment by kylem038** [comment]
Looks like we have a test already written for this specific issue in test/e2e/specs/geometry.js - I'm trying to reproduce to see if the test is a false positive or if the issue is resolved.

**Comment by kylem038** [comment]
We've confirmed this is still an issue that needs resolved and the test case does not cover this. I'm able to reproduce this pretty easily.

**Comment by kylem038** [comment]
@DavidGoldwasser I just merged in a fix for this issue. Let me know if you're able to recreate it but marking this as closed for now.
