### ISSUE TITLE
name change

### ISSUE THREAD

**Issue by bgschiller** [NatLabRockies/floorspace.js#256]

**Comment by macumber** [comment]
New name will be FloorspaceJS, repo name will be floorspace.js

sound good @bgschiller @shorowit

**Comment by shorowit** [comment]
Floorspace, not Floorplan? 😕

**Comment by macumber** [comment]
We thought floorplan was a little too general and not BEM enough, I don't want people thinking this is a general purpose architectural widget.

**Comment by macumber** [comment]
NREL legal did the trademark search on Floorspace

**Comment by shorowit** [comment]
Seems fine then.

**Comment by macumber** [comment]
Just renamed the repo https://github.com/NREL/floorspace.js

- [x] Update references in text/documentation to FloorspaceJS
- [x] Make sure CI is still working
- [x] Make sure githubpages are working
- [x] Update icon

**Comment by macumber** [comment]
@bgschiller assigning to you

**Comment by bgschiller** [comment]
@macumber I think everything went off without a hitch!
