### ISSUE TITLE
Flip double_arrows.svg on collapse

### ISSUE THREAD

**Issue by ljbrackney** [NatLabRockies/floorspace.js#275]
Very minor nitpick.  The same svg is used for both expanding and collapsing objects, which is visually non-intuitive.  Need to create a mirrored version of double_arrows.svg and use for collapse.

**Comment by ljbrackney** [comment]
Also the collapse/expand icons might benefit from being just a smidge larger.

**Comment by shorowit** [comment]
I see the svg change between left and right facing arrows, but agree that they should be larger. I fear that new users will not pick up on the ability to expand the panes, which is currently required for certain operations (like defining window sizes).

**Comment by shorowit** [comment]
Weird. It works fine in chrome, but I also see the issue for the version embedded in OpenStudio.

**Comment by bgschiller** [comment]
Note to self: The svg seems to be not flipping because of old chromium embedded in Qt. This should be fixed automatically when OpenStudio updates Qt. However, we should increase the size of the icons a bit.

**Comment by bgschiller** [comment]
Ready for testing at https://327-pr-floorspace.js-nrel.surge.sh/
