### ISSUE TITLE
Unable to change choice menu selections when previewing geometry in editor

### ISSUE THREAD

**Issue by ljbrackney** [NatLabRockies/floorspace.js#276]
When using the preview button within the editor, the preview window opens normally.  Pan, rotate, zoom, and radio buttons all work okay.  Attempts to change story or render modes do not work.

Merging geometry and using preview Sub-Tab in the Application works fine.

**Comment by macumber** [comment]
The preview is implemented in OpenStudio so this issue really belongs there, https://github.com/NREL/OpenStudio/issues/2994
