### ISSUE TITLE
Space and zone colors are mismatched and not sticky

### ISSUE THREAD

**Issue by ljbrackney** [NatLabRockies/floorspace.js#279]
Setting space and zone colors within the editor or app don't remain synced.  See the following screenshots.  In this case, I assigned Space Types within the App that came along with colors.  I created and assigned Thermal Zones within the editor's Assignment Sub-Tab.  The colors do not remain sticky when returning to the editor and navigating back to the assignment Sub-Tab - they always appear black.

![space1](https://user-images.githubusercontent.com/2230150/34585244-cccd486c-f153-11e7-96be-1d176a18e469.png)
![space2](https://user-images.githubusercontent.com/2230150/34585249-cfcf52a8-f153-11e7-86d0-d03dae6f2492.png)
![space3](https://user-images.githubusercontent.com/2230150/34585255-d30ae20c-f153-11e7-84d9-a8a12f96cb68.png)

![zone1](https://user-images.githubusercontent.com/2230150/34585261-d81bd4b8-f153-11e7-9320-4e606cf41e9e.png)
![zone2](https://user-images.githubusercontent.com/2230150/34585265-dafbc67a-f153-11e7-8a2e-221e77d4a4b6.png)

**Comment by ljbrackney** [comment]
This problem seems limited to the editor's behavior in the Assignments Sub-Tab.

**Comment by macumber** [comment]
I think this is really an OpenStudio bug https://github.com/NREL/OpenStudio/issues/2969
