### ISSUE TITLE
Confusing filled area for some polygons

### ISSUE THREAD

**Issue by shorowit** [NatLabRockies/floorspace.js#281]
Two examples below. The second one doesn't bother me as much, but the first one is quite confusing.
[FloorspaceJS.webm.txt](https://github.com/NREL/floorspace.js/files/1644091/FloorspaceJS.webm.txt)
[FloorspaceJS2.webm.txt](https://github.com/NREL/floorspace.js/files/1644095/FloorspaceJS2.webm.txt)

**Comment by macumber** [comment]
@shorowit personally I don't find these confusing at all

@DavidGoldwasser @ljbrackney if you download these webm videos and watch them do you find the presentation of polygon areas before clicking to be confusing?

**Comment by shorowit** [comment]
This came up in my demo to DOE where I couldn't see the map to trace over it due to this issue. Here's a better example where I can't figure out where the next vertex is supposed to be because it's covered by the polygon:

[FloorspaceJS3.webm.txt](https://github.com/NREL/floorspace.js/files/1816234/FloorspaceJS3.webm.txt)

**Comment by ljbrackney** [comment]
I think it might be confusing the first time someone was using the tool, but after you know what it's doing it's not too bad.  The third example is problematic - need more transparency in the polygon.

**Comment by shorowit** [comment]
I’d be fine with increased transparency if that’s easier.

**Comment by bgschiller** [comment]
Ready for testing at https://325-pr-floorspace.js-NREL.surge.sh

**Comment by shorowit** [comment]
Much better, thanks!
