### ISSUE TITLE
Temporarily hide untranslated items

### ISSUE THREAD

**Issue by macumber** [NatLabRockies/floorspace.js#290]
- [ ] Story multiplier
- [ ] Ground floor offset
- [ ] Ground azimuth angle
- [ ] Ground tilt slope
- [ ] Pitched roof

**Comment by macumber** [comment]
If you want to do this with an init config option that is fine otherwise just a temporary todo comment to mark the commented out code

**Comment by bgschiller** [comment]
@macumber I think the best way to do this is by adding a stylesheet to hide those items when you're  initializing the app. No extra api function is needed:

```
const rules = `
  [data-column="multiplier"] {
    display: none;
  }
  .ground-props-drawer {
    display: none;
  }
  .editable-select-list option[value="pitched_roofs"] {
    display: none;
  }
  [data-column="pitched_roof_id"] {
    display: none;
  }`;
const style = document.createElement('style')
style.type = 'text/css';
style.innerHTML = rules;
document.head.appendChild(style);
```

**Comment by macumber** [comment]
This is awesome, thanks @bgschiller !

Does it matter if I evaluate this before or after calling init?

**Comment by bgschiller** [comment]
No problem :)

And it's fine to run this whenever (before or after init).
