### ISSUE TITLE
Need a way to update floorplan while running

### ISSUE THREAD

**Issue by macumber** [NatLabRockies/floorspace.js#294]
After I export a floorplan and merge it with my application, I get new objects in my application.  I want to update the objects in the floorspace editor with ids pointing to those new objects.  I have an updated JSON file.  If I do importLibrary I get duplicate objects.

**Comment by macumber** [comment]
I can call openFloorplan with the updated JSON, is that ok?

**Comment by macumber** [comment]
Calling openFloorplan seems to work,  I want to run this by @bgschiller, if he thinks the general approach is ok then I am fine to close this.

The most noticeable thing is that openFloorplan resets the zoom to fit all geometry.  Might want an option to keep current zoom when opening the file?  The editor does seem to preserve the tab you are on when re-opening.

**Comment by macumber** [comment]
Might need some tests for this?

**Comment by bgschiller** [comment]
notes from meeting:
calling openFloorplan is safe to do. We'll add an option to openFloorplan to prevent zooming to fit
