### ISSUE TITLE
Issue with segmented edges

### ISSUE THREAD

**Issue by fsudaman** [NatLabRockies/floorspace.js#298]
![segmented lines](https://user-images.githubusercontent.com/9958226/35902340-f3986c24-0c2e-11e8-9283-ad067b78dc41.png)
Intersecting and Matching had several flaws, despite being drawn in 2D and with grid lines. When importing to SketchUp, the drawing appears to have small number of errors relating to segmented edges (see image attached)

**Comment by macumber** [comment]
Thanks for the feedback!  If you are using FloorspaceJS with OpenStudio we have made several improvements to the translation of FloorspaceJS to OpenStudio in OS 2.4.1: https://github.com/NREL/OpenStudio/releases/tag/v2.4.1

If you are able to give it a try in that release it would be very helpful for us to know if you problems are relieved at all

**Comment by fsudaman** [comment]
Hi Dan,
OpenStudio 2.4.1 has resolved the co-linear line issue, seems it now auto-intersects, which eliminates the need to use the 'intersect' function, which side-steps a significant problem ('intersect' has a tendency to shatter models). Here is a response from our engineer using the tool: "Thanks for your response, I've had a play around with the new release, really appreciating how easy matching has become!"

On separate note, our engineer are using this extensively and has come across a number of potential improvements. I would imagine raising a ticket for each will create a lot of noise. Do you have a preference on how we best provide those feedback to you/community? 

Thanks,
Fadrian Sudaman

**Comment by macumber** [comment]
Hi @fsudaman feedback through github is great!  We have one more release left in our development (milestone 0.8 on 3/30/2018).  We want to prioritize usability issues from users in this last release.  After that we are hoping that software developers using the tool will continue to improve it for their needs.

**Comment by fsudaman** [comment]
In that case I think what is raised in this ticket can be considered done and close. I will raise separate tickets for other improvements. Thanks again for your help.
