### ISSUE TITLE
Improvement to image scaling

### ISSUE THREAD

**Issue by fsudaman** [NatLabRockies/floorspace.js#300]
Image importing is used to overlay drawings on the map, or over the previous floor, so that the floorplan can be traced out. However, currently these images can't be scaled numerically, instead they are resized manually with the cursor. Images also resize from the centre, which means you have to keep adjusting its position as you go.

SketchUp lets you resize an image numerically (ie apply a scaling factor). Since subsequent drawings are usually to the same scale, manually sizing the first image, then somehow applying the same scale (and positioning) to subsequent images, would allow quicker, more consistent drawing of geometry.

**Comment by shorowit** [comment]
At a minimum, it seems like we should change the behavior so that images resize from the corner being manipulated, not the center.

**Comment by macumber** [comment]
Also make the numeric scaling factor editable

**Comment by shorowit** [comment]
Looks good!

**Comment by fsudaman** [comment]
Thanks guys
