### ISSUE TITLE
Space deform occasionally 

### ISSUE THREAD

**Issue by fsudaman** [NatLabRockies/floorspace.js#301]
Our engineer had encountered the following issue a few times. When drawing geometries a space will suddenly and unexpectedly deform occasionally. It seems as though the geometry is generated incorrectly, but the issue is not visible until the relevant line is modified in some way. Please see the attached PDF that demonstrates the issue observed and OSM file to reproduce the problem. 

[New Geometry Test - Bug Report.pdf](https://github.com/NREL/floorspace.js/files/1715449/New.Geometry.Test.-.Bug.Report.pdf)

[New geometry test.zip](https://github.com/NREL/floorspace.js/files/1715451/New.geometry.test.zip)

**Comment by bgschiller** [comment]
Note to self: It's possible that "canonicalizing" the geometry after any drawing action could go a long way towards fixing this issue (and others).

Try adding the tests for this, using OpenStudio's idea of 'circular equals': same vertex positions, but potentially wrapping at a different point.

Even if we can't get the canonicalization done in time, the tests could be useful for a future implementer.

**Comment by shorowit** [comment]
Was playing around with the tool and created a reproducible deformity. Open the attached file and make a drawing change as indicated in the video.

[deformity.json.txt](https://github.com/NREL/floorspace.js/files/1975432/deformity.json.txt)
[FloorspaceJS.webm.txt](https://github.com/NREL/floorspace.js/files/1975436/FloorspaceJS.webm.txt)

Results in this:
![image](https://user-images.githubusercontent.com/5861765/39643750-04c7caec-4f93-11e8-886f-4d50d03b3109.png)

**Comment by bgschiller** [comment]
I downloaded Scott's `deformity.json` file and saw that, according to the current version of floorspace, Space 1-2 is _already_ invalid at the time of import. (We don't warn about this, but you can check by calling the `validateFaceGeometry` function manually). The error is:
> error: "An edge is being touched by a vertex on the same face at (50, 45)"

To me, this indicates that we're catching this issue upstream. It would be impossible to create `deformity.json` with today's version of floorspace. I believe there are other bugs where floorspace incorrectly raises similar error messages. Those are false positives of the `validateFaceGeometry` function. However, we are now correctly identifying _this_ invalid case, so I think it's safe to close this issue.
