### ISSUE TITLE
Spaces created but do not show on Preview

### ISSUE THREAD

**Issue by Diotti** [NatLabRockies/floorspace.js#334]
Hi. I created a test building with two floors and the spaces were properly created, but I couldn't see the 3d model under the preview tab not the preview button between "refresh" and "merge" buttons of the editor screen.

The text under debug is pasted below:

QtWebEngine Remote Debugging
http://127.0.0.1:51321/
Floorspace JS
qrc:///library/embeddable_geometry_editor.html

**Comment by macumber** [comment]
Did you press the merge button to merge your floorplan with the current OSM?

**Comment by Diotti** [comment]
Hi macumber, 

Thank you,
Yes, I did press merge after placing the windows.

PS.
I'm doing the exercise on pages 42, 43 of Building Energy Modeling with OpenStudio, which you co-authored.

**Comment by Diotti** [comment]
I just installed OpenStudio v2.6 and Floorspace JS works perfectly now.
