### ISSUE TITLE
Impossible to set snapMode via api in the html embeddable version

### ISSUE THREAD

**Issue by Jopenergy** [NatLabRockies/floorspace.js#335]
Little bug in floorspace.js-0.8.0/src/api.js ?

I slightly modified the api settings:

![capture d ecran 2018-10-29 a 12 58 57](https://user-images.githubusercontent.com/15978235/47648547-9bbabe00-db7a-11e8-8c4d-dca28e5f6d0f.png)

Neither "grid-strict" nor "grid-verts-edges" are accepted for snapMode:

![capture d ecran 2018-10-29 a 12 52 03](https://user-images.githubusercontent.com/15978235/47648284-dbcd7100-db79-11e8-9565-cbaa0fa4d5c2.png)
![capture d ecran 2018-10-29 a 12 53 11](https://user-images.githubusercontent.com/15978235/47648285-dbcd7100-db79-11e8-947b-c454955c5eda.png)

Thank you in advance,

**Comment by bgschiller** [comment]
This is fixed and live on develop
