### ISSUE TITLE
Problem with grid size under 1 unity

### ISSUE THREAD

**Issue by Jopenergy** [NatLabRockies/floorspace.js#336]
When grid spacing is under unity (for example 0.1ft or 0.1m), there is a bug when trying to intersect two spaces.

1. let's draw a space on the 0.1ft grid : 
![bug-grid-1](https://user-images.githubusercontent.com/15978235/47659618-a0d93680-db95-11e8-955d-5b2ff08880e0.png)

2. we can check that the space is not snapped on the 1ft grid:
![bug-grid-2](https://user-images.githubusercontent.com/15978235/47659679-c1a18c00-db95-11e8-9a8b-f120d3c334d9.png)

3. now, let's go back to the 0.1ft grid and draw a new space on this 0.1ft grid. The new space is ok: the vertices are on the the 0.1ft grid. However, the old space is modified:
![bug-grid-3](https://user-images.githubusercontent.com/15978235/47659689-c6664000-db95-11e8-8e2e-db93ef105369.png)

4. going back to the 1ft grid, we can check that the old space has been automatically modified to snap to the 1ft grid, without any reason...
![bug-grid-4](https://user-images.githubusercontent.com/15978235/47659710-ce25e480-db95-11e8-93dc-cfbaec104d66.png)

5. in order to make sure that the problem comes from the 0.1ft grid, we do the same workflow but starting with a 1ft grid. In this cas, everything works properly:
![image](https://user-images.githubusercontent.com/15978235/47659724-d54cf280-db95-11e8-949f-8948d34222e3.png)

Thank you for your help!

**Comment by DavidGoldwasser** [comment]
I'm hitting this as well with 2.5' grid. I have video if interested but here are few screenshots. Note, while my grid is larger than 1, it isn't a multiple of 1. I do see same issue with grid size of 0.5'.

I started with rectangle of entire footprint then started drawing new spaces that cut into that. It over-cuts to whole foot leaving a gap. If I try to fill the gap by enlarging the primary space then it goes past my grid the other direction.

![screen shot 2018-11-07 at 2 49 01 pm](https://user-images.githubusercontent.com/4857055/48163262-79245580-e29c-11e8-8aed-8b6fefbcc111.png)

![screen shot 2018-11-07 at 1 26 46 pm](https://user-images.githubusercontent.com/4857055/48163273-804b6380-e29c-11e8-8441-0ea2730fbb74.png)

**Comment by bgschiller** [comment]
This has been implemented and is live on develop. We've added tests that use sub-unit grid sizes.
