### ISSUE TITLE
Export fail due to some unknown internal limits

### ISSUE THREAD

**Issue by fsudaman** [NatLabRockies/floorspace.js#341]
Floorspace appears to have a limit to how large a file can be, after which it can’t be exported (/saved). This is mostly a problem when you import images for various floors, as saving/reloading requires you to delete your images and replace them. Image import is quite manual, and you have to resize by eye, so this is both inconvenient and can cause errors.

The attached JSON file contains a half-built model geometry, in which drawing any new spaces prevents the model from being exported (“Download failed – Network error”). This was tested across multiple machines, in chrome. However, removing the image allows the model to be successfully exported.
This issue may be linked to the size of the file, as replacing some of the more complex spaces with simpler ones allows more spaces to be created before hitting the limit.

[Export Bug.zip](https://github.com/NREL/floorspace.js/files/2665512/Export.Bug.zip)

**Comment by bgschiller** [comment]
Thanks for the report, and the test case. It looks like we're running up against Chrome's 2mb limit for download URLs ( described at https://craignicol.wordpress.com/2016/07/19/excellent-export-and-the-chrome-url-limit/)

That same post describes a solution that doesn't look too tricky.

**Comment by bgschiller** [comment]
This has been implemented and works with the test case you provided.

**Comment by fsudaman** [comment]
Brilliant. Thanks Brian.
