### ISSUE TITLE
Repeating Window Bug

### ISSUE THREAD

**Issue by fsudaman** [NatLabRockies/floorspace.js#349]
Repeating windows aren't placed at the correct height (see attached screenshots in the zip file)
 
The windows seem to be placed at 'Sill Height' above the ground, rather than 'Sill Height' + 'Sum of Lower Floor Heights'
 
The windows are still associated with the correct spaces (See 'L4 Screenshot' in the attached zip file), they just appear at the wrong position

[Repeating Windows Bug.zip](https://github.com/NREL/floorspace.js/files/2758198/Repeating.Windows.Bug.zip)

**Comment by bgschiller** [comment]
@macumber I'm thinking this is a bug later down the chain, yes? maybe in [NREL/OpenStudio](https://github.com/NREL/OpenStudio)?

**Comment by macumber** [comment]
Very possible, @fsudaman are you using OpenStudio to translate the FloorspaceJS file?  If so, which version of OpenStudio?

**Comment by Mkellyeng** [comment]
Hi, I work with @fsudaman 
We do use OpenStudio to translate FloorspaceJS files, we're currently using 2.7.0. I'm not aware of any other way to get FloorspaceJS files into IDF format for EnergyPlus?

What's interesting is that windows defined using Window to Wall Ratio come through correctly, but using single or repeating windows places them on the ground floor.

**Comment by macumber** [comment]
Moved to https://github.com/NREL/OpenStudio/issues/3405
