### ISSUE TITLE
BIM import/export

### ISSUE THREAD

**Issue by Mathadon** [NatLabRockies/floorspace.js#351]
All,
Building Information Modeling is gaining attention in my region (Belgium). I'm trying to assess how hard it would be to extend floorspace.js such that it can import and/or export to/from the ifc file format. Is someone able to comment on this? 
Thanks!

edit: I guess that this is linked to #225

**Comment by macumber** [comment]
We did not build in an OSM (3D) to FloorspaceJS (2D) translator because it would be very lossy.  You could translate the floorplan but would lose information about 3D details.  I'm not sure if IFC has a 2D floorplan view, if so maybe that could be exported to the FloorspaceJS JSON format?

**Comment by macumber** [comment]
The other pathway, FloorspaceJS JSON (2D) to IFC, is certainly possible.  It would just be a translator of the JSON format to IFC.

**Comment by Mathadon** [comment]
Thanks! I'll close this for now.
