### ISSUE TITLE
On https://nrel.github.io/floorspace.js/ open and save floorplan icons go away after opening floorplan

### ISSUE THREAD

**Issue by DavidGoldwasser** [NatLabRockies/floorspace.js#353]
In the past I could open, edit and save an existing floorplan. Now when I open a floorplan, the open and save icons in the interface go away, and I can't save changes being made back to my computer.

cc: @macumber

**Comment by DavidGoldwasser** [comment]
Additional details: If I make a floorspace.json in web interface, save it and then open it things are fine. I only seem to see this issue if I open in web interface a floorspace.json made by OpenStudio Application.

**Comment by DavidGoldwasser** [comment]
@macumber this only happens when I load a floorplan made by OS app. If I download a floorplan made in web interface, I can then later re-upload it and not lose the import/save icon.

A work around for me to get space type and construction sets into web interface seems to be by load library.

I assume the case for this could be that the web interface is a development branch and the file format can change and may not be stable when importing json files from older versions?

**Comment by macumber** [comment]
@DavidGoldwasser this should be in the OpenStudio repo right?

**Comment by DavidGoldwasser** [comment]
@macumber No, it is an issue I hit in the web interface, where certain files don't open properly. Maybe they should be versioned, and it doesn't attempt to open it?

The idea at first was to load model from app to here, edit it, save it, then load it back in App, but as soon as I load it, the option to save is gone (in the web interface). 

My work around for now can be to lean on the library, as long as I only want to load resources form the model. Loading the exact same json as a library doesn't break anything.

**Comment by DavidGoldwasser** [comment]
@macumber identified that this can be addressed by changing `show_import_export": false` to `show_import_export": true` before uploading a json file written by OS app.
