### ISSUE TITLE
Window Deletion Bug

### ISSUE THREAD

**Issue by Mkellyeng** [NatLabRockies/floorspace.js#355]
If you delete a space that has a window, by using the delete button, you cannot draw any new spaces on that floor.

It appears using the delete button to delete a space doesn't remove windows that are associated with that space, leaving them with a dangling reference. 

This results in very strange behaviour that prevents you from drawing any new spaces on that floor. The drawing tools behave as though you're using 'Polygon' (regardless of whether you have rectangle or polygon selected), but you can't accept the shape, finalising the space. 

This behaviour is only seen on the floor where the bug was triggered, other floors still behaviour as normal. Saving the file and re-opening retains the bug, but saving, manually removing the window, and re-opening, removes the bug.

See the attached zip file for examples of both the bugged and fixed state

[Window Deletion Bug.zip](https://github.com/NREL/floorspace.js/files/3209733/Window.Deletion.Bug.zip)
![Window Deletion Bug](https://user-images.githubusercontent.com/46730121/58216105-4a556480-7d40-11e9-810c-ee309ee863ab.PNG)

**Comment by bgschiller** [comment]
Hi @Mkellyeng, A couple other people have noticed this same problem! I think we have a patch for it over in #356 , but some of the (unrelated) tests are failing. I'm hoping to find time soon to fix up those tests so I can merge the branch in.

**Comment by bgschiller** [comment]
Closing, as I believe this is fixed now that #356 is merged.

**Comment by Mkellyeng** [comment]
@bgschiller was this fix only for the open studio version? I can still replicate in the online version
![image](https://user-images.githubusercontent.com/46730121/111387175-6c805980-8701-11eb-8326-8fc9eb069a4a.png)

**Comment by kylem038** [comment]
@Mkellyeng I've tested this out on the webapp and it appears to have been resolved. Let us know if you're still able to recreate it.

**Comment by Mkellyeng** [comment]
Re-tested, Issue is resolved! Fantastic!
